README.md

I've added a simple instruction to set up the local environment so that Han does not need to walk through the SETUP with every new contributor.

add instructions of local env setup

---

src/App.js

Switched newsFeed and twttierFeed location, then move  historyGraph before twitterFeed based on Chen's request

page display adjustment

---

package-lock.json
package.json
src/App.js
src/data/info.json

I've added the information page where if you add info into the info.json file, it will automatically render it into the information page. This however makes it harder to customise, but reduces code smell. Since the information page is static information, we could potentially make it all hardcoded in and therefore have more customisation.

add info page

---

src/App.js

Hi all, love what you're doing here.

Fix plurality

---

src/App.css
src/ConfirmedMap.css
src/ConfirmedMap.js

Code to add the map key from #43.

Add map key

---

src/App.css
src/App.js

Navigation will now stick to top of page when scrolling down.

Add sticky nav bar

---

package-lock.json
package.json
public/index.html
src/App.js
src/socialMediaShare/SharedButtons.css
src/socialMediaShare/SharedButtons.js
src/socialMediaShare/SocialMediaShareModal.js
src/socialMediaShare/constants.js/index.js

- add social media share buttons with modal
A view of social medias I am using.

feat: add social media share buttons

---

src/App.js

- Update title font family to match the global style
- Update title text
- Add plurality to new case(s)

Update graph titles and labels

---

package-lock.json
package.json
src/App.js
src/socialMediaShare/SharedButtons.css
src/socialMediaShare/SharedButtons.js
src/socialMediaShare/SocialMediaShareModal.js
src/socialMediaShare/constants.js/index.js

- remove antd and other css lib
- update social media lib
A view of UI on different screen size

Update social media share

---

src/data/flight.json
src/data/mapdataCon.json
src/data/mapdataHos.json

-Daily Data Update: Mar22
-Update mapdataCon.json, flight.json, flight.json to latest data.
-Tested the flight function is working fine (sorting correctly). Tested map function is reflecting latest data.

Daily Data Update: Mar22

---

src/App.css
src/App.js

add the daily increased number for the first three columns

update style and add daily data

---

src/Flights.js

flight search complete.
Show 5 flight information by default.
Results are sorted by date arrival from latest to oldest.

Box flight

---

src/App.js
src/StateGraph.js

#9.
Dynamically sorts the legend by the number of cases, though this does mean the colours will change day-to-day.
**Widget**
**Full page**

State-level case graph

---

package-lock.json
src/App.js

Remove existing series from graph

---

.gitignore
src/ConfirmedMap.css
src/ConfirmedMap.js

Gelocation and Zoom Controls on Desktop
Only Geolocation on mobile

Update Map To Include Geolocation and Nav Controls

---

public/index.html
src/App.js

A screenshot of how it would look like

Tooltip modifications

---

package-lock.json
package.json
src/App.css
src/App.js
src/fallback.js

Adding routes so people can go back to certain pages. Also so that we can implement SEO functionality following this update.

Add routes

---

src/data/flight.json
src/data/mapdataCon.json
src/data/mapdataHos.json
src/data/mapdataarea.json

Daily Update Mar30

---

src/Acknowledgment.js
src/faq.js

Minor Change

---

src/Acknowledgment.js
src/App.css

Fixes #143 
**Changes**  
- add cursor pointer to datasource
- fix NSW health link (missing protocol on the link)
- some minor text formatting
**To Verify**    
- checkout branch `git checkout <branch-name>`
- build `npm start`
- verify changes above
**Merge Instructions**  
Merge after approval

Fix Data acknowledgements NSW health link

---

src/data/flight.json
src/data/mapdataCon.json
src/data/mapdataarea.json

Daily Data Update Apr3

---

public/index.html

Adding Imagemeta tags to support image thumbnails

adding image meta tags

---

public/index.html

Adding image meta tags for twitter

Adding image meta tags for twitter

---

public/index.html

adding meta tags to improve SEO

adding meta tags to improve SEO

---

src/data/mapdataarea.json

-Update LGA data to Apr14
-Add Stonington data back.

Daily Data Update Apr14

---

src/App.css
src/HomePage/Area.js

add active case data

---

src/data/blogPosts.json

add blog 25/04/2020

---

src/data/blogPosts.json

Reverts covid-19-au/covid-19-au.github.io#336

Revert "add blog 21/05/2020"

---

src/data/blogPosts.json

Reverts covid-19-au/covid-19-au.github.io#337

Revert "Revert "add blog 21/05/2020""

---

src/data/flight.json

-Update flight information.
-Age/gender/LGA data will be postponed to tomorrow morning due to scraper issue

Daily Data Update Jul 19 1/2

---

src/dvAna.js

dvAna fix to use https

---

src/aboutUs/teams_helper.js

Hi again everyone!
Missed Andrew's post last semester, so just updating the data file with my details.

Add Matt's details

---

src/HomePage/ConfirmedMap.js
src/HomePage/ConfirmedMap/layers/LayerFillPolyCases.js

-dvAna distinguish slider date now.
-Only added 3 lines. Other code changes were done by prettier which only affect code text format.

dvAna update

---

src/data/flight.json

-Daily Data Update Aug 6 part 1 of 2.
-Map and age/gender data will be updated tomorrow due to scraper issue

Daily Data Update Aug 6 (1/2)

---

src/HomePage/ConfirmedMap/AxiosAnalytics.js

Bug Fix AxiosAnalytics

---

src/data/ageGender.json

Daily Data Update Aug 12
